# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c2640786dc740243607106ff36a178ca9cd0b7d68cf9a63c0f68443e0c06785526ec552af9dff6eb74a380064b85f7dc136687370f9c9c0042d88e4307eb55a

test:
  secret_key_base: 10d7824fe24e24c2ba4af148fe4da87c151dbe67fd08f2ffb9d462a5f339ad1b3e5990c6b0f274ae2f54d9bae2f098f57a8129de16959d1719bc2e43a8937909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
